### ISSUE TITLE
add fiducial locations to T1w json sidecars

### ISSUE THREAD

**Issue by Arshitha** [nih-megcore/hv_protocol#5]
Fiducial locations or `AnatomicalLandmarkCoordinates` in T1w JSON sidecars are used for co-register of the subject's MEG data. During testing, @jstout211 found that this field was missing from [v1.0.0 of the dataset on openneuro](https://openneuro.org/datasets/ds004215/versions/1.0.0). For any MEG analysis, this is a required field.

**Comment by jstout211** [comment]
The updated tags designating fiducial locations in voxel coordinates of the run01 T1w dataset should allow for automated import into bids compatible MEG processing pipelines.
