### ISSUE TITLE
Datalad Download Instructions - defaulting to v1.0.0 (not current)

### ISSUE THREAD

**Issue by jstout211** [nih-megcore/hv_protocol#9]
Here are the download instructions for datalad.
datalad install https://github.com/OpenNeuroDatasets/ds004215.git

This will download version 1.0.0.  You can switch to 1.0.1 manually by doing git checkout 'tags/1.0.1', but this is not intuitive for everyone.

This is possibly an openneuro issue or we need to update the main/HEAD to the v 1.0.1 tag (see below after checking out the 1.0.1 version).

![image](https://user-images.githubusercontent.com/2371720/201671568-adbe9d92-bbda-4d4e-ba36-274f5fcd6bd5.png)

**Comment by ericearl** [comment]
I wonder if we should post an issue to the openneuro or datalad repositories? Maybe what does the OpenNeuro documentation say is the right way to download datasets via CLI?

**Comment by jstout211** [comment]
Posted this to openneuro -- they are going to re-sync.  Will test after the update and potentially close this.
